services:
  lb:
    ports:
      - {{LB_HTTP_PORT}}:80
      - {{LB_HTTPS_PORT}}:443
    volumes:
      - {{LB_NGINX_CONF}}:/etc/nginx.conf
      - {{LB_NGINX_CONF_D}}:/etc/nginx/conf.d
      - {{LB_NGINX_WEBROOT}}:/webroot
      - {{LB_NGINX_CERTS}}:/certs

  mariadb:
    volumes:
      - {{MARIADB_DATA_PATH}}:/var/lib/mysql

  postgres:
    volumes:
      - {{POSTGRES_DATA_PATH}}:/var/lib/postgresql/data

  redis:
    volumes:
      - {{REDIS_DATA_PATH}}:/data

  authentikapp:
    volumes:
      - {{AUTHENTIK_MEDIA}}:/media
      - {{AUTHENTIK_TEMPLATES}}:/templates
      - {{AUTHENTIK_USER_SETTINGS_PY}}:/data/user_settings.py:ro

  authentikworker:
    volumes:
      - {{AUTHENTIK_MEDIA}}:/media
      - {{AUTHENTIK_TEMPLATES}}:/templates
      - {{AUTHENTIK_USER_SETTINGS_PY}}:/data/user_settings.py:ro
      - {{AUTHENTIK_CERTS}}:/certs

  nextcloudapp:
    volumes:
      - {{NEXTCLOUD_WEBROOT}}:/var/www/html
      - {{NEXTCLOUD_DATA}}:/var/www/html/data
      - {{NEXTCLOUD_WWW_CONF}}:/usr/local/etc/php-fpm.d/www.conf:ro

  nextcloudweb:
    volumes:
      - {{NEXTCLOUD_WEBROOT}}:/var/www/html:ro
      - {{NEXTCLOUD_NGINX_CONF}}:/etc/nginx/nginx.conf

  nextcloudcron:
    volumes:
      - {{NEXTCLOUD_WEBROOT}}:/var/www/html
      - {{NEXTCLOUD_DATA}}:/var/www/html/data

  elasticsearch:
    volumes:
      - {{ELASTICSEARCH_DATA}}:/usr/share/elasticsearch/data:rw

