{{SERVICES_PLACEHOLDER}}
  jellyfin:
    env_file: {{JELLYFIN_ENV_FILE}}
    volumes:
      - {{JELLYFIN_CONFIG_PATH}}:/config
      - {{JELLYFIN_DATA_PATH}}:/data

  xteve:
    volumes:
      - {{XTEVE_CONF_PATH}}:/home/xteve/conf
